title: Burning in Ah Shey See village, Kale Township, Sagaing Region
##description: This website demonstrates how to easily publish and display an interactive map made with Folium. It features some hot spots around Ithaca, NY.
logo: AhSheySee.jpg
